package com.discordlogger.command;

import com.discordlogger.DiscordLogger;
import com.discordlogger.config.ConfigMigrator;
import org.bukkit.ChatColor;
import org.bukkit.command.CommandSender;

import java.io.File;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.List;

/**
 * Replaces config.yml with this build's shipped default, keeping a backup.
 *
 * <p>Exists for the one case {@link ConfigMigrator} deliberately refuses to handle:
 * a config whose schema is newer than the running plugin. Migration only ever runs
 * forward, so there is no automatic way back — this is the manual escape hatch.
 *
 * <p>It is destructive by design, so it does not migrate, merge or preserve
 * anything: the point is to get back to a file this build fully understands. The
 * old file is renamed rather than deleted, with a timestamp, so an existing
 * config.old.yml from a previous migration is never overwritten.
 */
public final class Regen implements Subcommand {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss");

    private final DiscordLogger plugin;

    public Regen(DiscordLogger plugin) {
        this.plugin = plugin;
    }

    @Override public String name() { return "regen"; }
    @Override public String description() { return "Rebuilds config.yml from this build's default (backs up the current one)."; }
    @Override public String permission() { return "discordlogger.regen"; }

    @Override
    public boolean execute(CommandSender sender, String[] args) {
        // Destructive, so require the word rather than acting on a bare typo of
        // "reload" — the two commands are one keystroke apart.
        if (args.length == 0 || !args[0].equalsIgnoreCase("confirm")) {
            sender.sendMessage(ChatColor.YELLOW
                    + "This replaces config.yml with the default from this build. "
                    + "Your current file is backed up, but your settings are NOT carried over.");
            sender.sendMessage(ChatColor.YELLOW + "Run " + ChatColor.WHITE
                    + "/discordlogger regen confirm" + ChatColor.YELLOW + " to go ahead.");
            return true;
        }

        final File dataFolder = plugin.getDataFolder();
        final File config = new File(dataFolder, "config.yml");

        final String defaultText;
        try (InputStream in = plugin.getResource("config.yml")) {
            if (in == null) {
                sender.sendMessage(ChatColor.RED + "This build has no bundled config.yml to restore from.");
                return true;
            }
            defaultText = new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (Exception ex) {
            sender.sendMessage(ChatColor.RED + "Could not read the bundled config.yml: " + ex.getMessage());
            return true;
        }

        String backupName = null;
        try {
            if (config.exists()) {
                backupName = "config.backup-" + LocalDateTime.now().format(STAMP) + ".yml";
                Files.move(config.toPath(), new File(dataFolder, backupName).toPath(),
                        StandardCopyOption.REPLACE_EXISTING);
            }
            Files.createDirectories(dataFolder.toPath());
            Files.writeString(config.toPath(), defaultText, StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        } catch (Exception ex) {
            sender.sendMessage(ChatColor.RED + "Could not rewrite config.yml: " + ex.getMessage());
            plugin.getLogger().severe("Config regen failed: " + ex);
            return true;
        }

        plugin.reloadConfig();
        boolean ok = plugin.applyRuntimeConfig();

        Integer shipped = ConfigMigrator.shippedVersion(plugin, "config.yml");
        sender.sendMessage(ChatColor.GREEN + "config.yml rebuilt"
                + (shipped != null ? " at schema v" + shipped : "") + ".");
        if (backupName != null) {
            sender.sendMessage(ChatColor.GRAY + "Previous file saved as " + backupName);
        }
        if (!ok) {
            sender.sendMessage(ChatColor.RED
                    + "The new config has no webhook URL yet — set webhook.url, then run /discordlogger reload.");
        }
        plugin.getLogger().info("config.yml was regenerated by " + sender.getName()
                + (backupName != null ? " (backup: " + backupName + ")" : ""));
        return true;
    }

    @Override
    public List<String> tabComplete(CommandSender sender, String[] args) {
        return args.length == 1 ? List.of("confirm") : Collections.emptyList();
    }
}
