####################################################################################################################################
#                                                                                                                                  #
#    /$$$$$$$  /$$                                               /$$ /$$                                                           #
#   | $$__  $$|__/                                              | $$| $$                                                           #
#   | $$  \ $$ /$$  /$$$$$$$  /$$$$$$$  /$$$$$$   /$$$$$$   /$$$$$$$| $$        /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$    #
#   | $$  | $$| $$ /$$_____/ /$$_____/ /$$__  $$ /$$__  $$ /$$__  $$| $$       /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$   #
#   | $$  | $$| $$|  $$$$$$ | $$      | $$  \ $$| $$  \__/| $$  | $$| $$      | $$  \ $$| $$  \ $$| $$  \ $$| $$$$$$$$| $$  \__/   #
#   | $$  | $$| $$ \____  $$| $$      | $$  | $$| $$      | $$  | $$| $$      | $$  | $$| $$  | $$| $$  | $$| $$_____/| $$         #
#   | $$$$$$$/| $$ /$$$$$$$/|  $$$$$$$|  $$$$$$/| $$      |  $$$$$$$| $$$$$$$$|  $$$$$$/|  $$$$$$$|  $$$$$$$|  $$$$$$$| $$         #
#   |_______/ |__/|_______/  \_______/ \______/ |__/       \_______/|________/ \______/  \____  $$ \____  $$ \_______/|__/         #
#                                                                                     /$$  \ $$ /$$  \ $$                          #
#                                                                                    |  $$$$$$/|  $$$$$$/                          #
#                                                                                     \______/  \______/                           #
#                                                                                                                                  #
####################################################################################################################################

#############################
# D O C U M E N T A T I O N #
#############################

# Documentation for this config can be found at https://discordlogger.godtiergamers.xyz/config/v9/

###################
# WEBHOOK OPTIONS #
###################

webhook:
  url: "" # Discord webhook URL goes here, plugin will not function until present

##################
# FORMAT OPTIONS #
##################

format:
  # ONLY USED FOR PLAIN TEXT MESSAGES (EMBEDS DISABLED)
  # Usage (case-sensitive): HH=hours, mm=minutes, ss=seconds, dd=day, MM=month, yyyy=year
  time: "[HH:mm:ss, dd:MM:yyyy]"
  # Only used for plain text, for embeds edit author name
  name: ""
  # Show nicknames (if set) as "Nickname (RealName)" in all player-related logs
  nicknames: true

#################
# EMBED OPTIONS #
#################

embeds:
  enabled: true
  author: "Server Logs" # Can be modified for proxy servers (e.g. Survival, Creative)

  # Per-category colors (hex). Keys are case-insensitive; spaces become underscores.
  colors:
    player:
      join:    "#57F287"  # green
      quit:    "#ED4245"  # red
      chat:    "#5865F2"  # blurple
      command: "#FEE75C"  # yellow
      death:   "#ED4245"  # red
      advancement: "#2ECC71" # green
      teleport: "#3498DB" # blue
      gamemode: "#9B59B6" # purple
    server:
      start:   "#43B581"  # green
      stop:    "#ED4245"  # red
      command: "#EB459E"  # pink
      explosion: "#E74C3C" # red
    moderation:
      ban:              "#FF0000"  # red
      unban:            "#FF0000"  # red
      kick:             "#FF0000"  # red
      op:               "#FF0000"  # red
      deop:             "#FF0000"  # red
      whitelist_toggle: "#1ABC9C"  # teal
      whitelist:        "#16A085"  # dark teal



####################################################################################
#                                                                                  #
#     _                      _                ___         _    _                   #
#    | |    ___  __ _  __ _ (_) _ _   __ _   / _ \  _ __ | |_ (_) ___  _ _   ___   #
#    | |__ / _ \/ _` |/ _` || || ' \ / _` | | (_) || '_ \|  _|| |/ _ \| ' \ (_-<   #
#    |____|\___/\__, |\__, ||_||_||_|\__, |  \___/ | .__/ \__||_|\___/|_||_|/__/   #
#               |___/ |___/          |___/         |_|                             #
#                                                                                  #
####################################################################################

log:
  player:
    join: true # Player Join
    quit: true # Player Quit
    chat: true # Player Chat
    command: true # Commands executed by a player in-game
    death: true # Player Death (with death message)
    advancement: true # Logs when a player gets an advancement
    teleport: true # Logs when a player teleports
    gamemode: true # Logs when a players gamemode changes

  server:
    command: true # Commands executed via the server console/terminal
    start: true # Logged when the plugin/server starts
    stop: true # Logged on /stop / clean shutdown
    explosion: true # Log when an explosion occurs

  moderation:
    ban: true # Logs when a player has been banned
    unban: true # Logs when a player has been unbanned
    kick: true # Logs when a player has been kicked
    op: true # Logs when a player is granted op premissions
    deop: true # Logs when a players op permissions are revoked
    whitelist_toggle: true # Logs when the whitelist is enabled/disabled
    whitelist_edit: true # Logs when players are added/removed from the whitelist


# CONFIG VERSION V9, SHIPPED WITH V2.1.5
