name: DiscordLogger
main: com.discordlogger.DiscordLogger
version: ${project.version}
api-version: 1.21
author: LVCHLANN
description: Logs server events to a Discord channel via webhooks.

commands:
  discordlogger:
    description: DiscordLogger reload command
    usage: "/discordlogger reload"
    permission: discordlogger.reload
    aliases: [dlogger, dlog]

permissions:
  discordlogger.reload:
    description: Allows reloading DiscordLogger config
    default: op