name: DiscordLogger
main: com.discordlogger.DiscordLogger
version: 2.0.0
api-version: 1.21
author: LVCHLANN
description: Plain-text Discord logging for core server/player events.

# (optional, add later when we implement commands)
# commands:
#   discordlogger:
#     description: DiscordLogger admin commands
#     usage: /<command>
#     permission: discordlogger.admin
# permissions:
#   discordlogger.admin:
#     description: Allows use of /discordlogger
#     default: op
