name: Release (test branch)

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build with Maven (skip tests for speed)
        run: mvn -B -ntp -DskipTests clean package

      - name: Find built jar
        id: jar
        run: |
          file=$(ls -1 target/*.jar | grep -v -E 'sources|javadoc' | head -n1)
          echo "file=$file" >> "$GITHUB_OUTPUT"

      - name: Compute tag and name
        id: meta
        run: |
          sha="${GITHUB_SHA::7}"
          ts="$(date -u +'%Y.%m.%d')"
          echo "tag=v0.0.0-test-$ts-$sha" >> "$GITHUB_OUTPUT"
          echo "name=Test Build $ts ($sha)" >> "$GITHUB_OUTPUT"

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: .github/release-changelog-builder-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ steps.meta.outputs.tag }}" -m "Test release ${ { steps.meta.outputs.name } }"
          git push origin "${{ steps.meta.outputs.tag }}"

      - name: Create GitHub pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: true
          files: ${{ steps.jar.outputs.file }}
